apiVersion: batch/v1
kind: Job
metadata:
  name: print-num-02
spec:
  template:
    metadata:
      annotations:
        # disable istio on the pod due to this issue:
        # https://github.com/istio/istio/issues/11659
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: print-num
        image: codingcorp-docker.pkg.coding.net/nocalhost/public/alpine:latest
        command: ["sleep", "1"]
      restartPolicy: Never
  backoffLimit: 4
