apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      volumes:
        - name: foo
          configMap:
            name: ratings
      containers:
      - name: ratings
        image: codingcorp-docker.pkg.coding.net/nocalhost/bookinfo/ratings
        env:
          - name: DB_TYPE
            value: mysql
          - name: MYSQL_DB_HOST
            value: mysqldb
          - name: MYSQL_DB_PORT
            value: '3306'
          - name: MYSQL_DB_USER
            value: root
          - name: MYSQL_DB_PASSWORD
            value: password
          - name: SERVICE_VERSION
            value: v2
        volumeMounts:
          - name: foo
            mountPath: "/foo"
            readOnly: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        readinessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratings
data:
  foo: "bar"

